CampusDual/cd2024bfs2g1

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-detail/business-detail.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-home/business-home.component.html

- New business & refresh button in business-home
- Style changes in business-detail.

GAL-15 (Minor changes)

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-detail/business-detail.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/en.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/es.json

- Correction of some translations
- Remaining translations added

GAL-15 (Translation fixes)

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-detail/business-detail.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-detail/business-detail.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-detail/business-detail.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/en.json

- Visual bugs fixed
- Schedule translate of business-detail changed for Opening hours
- Change $ symbol for € symbol
- View of service cost deleted

GAL-15 (Visual Updates)

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-new/business-new.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-new/business-new.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/en.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/es.json
cd2024bfs2g1-model/src/main/resources/db/migration/V8__changes_businnes_table.sql

Aumentar la capacidad de teléfono y URL
Limitar la descripción a las filas permitidas

GAL-54 Cambiar el formato de los campos del formulario de negocio

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-new/business-new.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-new/business-new.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-new/routes-new.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-new/routes-new.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-new/routes-new.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/en.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/es.json
cd2024bfs2g1-model/src/main/java/com/campusdual/cd2024bfs2g1/model/core/service/RouteService.java

Cambiar el checkbox de borrador
Limitar el cuadro de descripción
Habilitar un desplegable para la dificultad
Validación de campos en blanco

Gal-68 Mejorar el formulario de subir rutas

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-new/view-all-landmark/view-all-landmark.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-new/view-all-landmark/view-all-landmark.component.ts

GAL-22: Arreglo en la tabla de landmarks

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-home/business-home.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-home/business-home.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/my-packs/pack-client/pack-client.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.html

GAL-G5-VisualImproves

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/my-packs/pack-client/pack-client.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/my-packs/pack-client/pack-client.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.html

GAL-G5-minorFixes

---

cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/en.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/es.json

Cambio de las traducciones en el titulo de nuevo negocio

GAL-61 change title new business

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/my-packs/pack-client/pack-client.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/my-packs/pack-client/pack-client.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/my-packs/pack-client/pack-client.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.ts

Gal g5 fix

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-detail/view-landmark-detail/view-landmark-detail.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-home/routes-home.component.ts

Últimos retoques a petición de Gema.

Ultimos retoques

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-detail/pack-detail.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-detail/pack-detail.component.html

Fix: Back and reserve button, default image size

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-new/add-landmark/add-landmark.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-new/routes-new.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-new/view-all-landmark/view-all-landmark.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-new/view-all-landmark/view-all-landmark.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/en.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/es.json
cd2024bfs2g1-model/src/main/java/com/campusdual/cd2024bfs2g1/model/core/service/RouteService.java

1. Poner en el formulario de rutas en que unidad va la duración
2. Capar los nombres a 70 caracteres en ambos formularios
3. Poner en el formulario de puntos de interés las coordenadas como obligatorio
4. Al cambiar a la pantalla de puntos de interés, poner algo que diga en que ruta estás

GAL-91: Editar el formulario de rutas y puntos de interés

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-new/business-new.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-new/pack-new.component.css

Cambio del color en en las opciones que están seleccionadas dentro de un o-combo

GAL-50: change color selection multiple o-combo

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-detail/business-detail.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-detail/business-detail.component.ts
cd2024bfs2g1-model/src/main/java/com/campusdual/cd2024bfs2g1/model/core/service/business/BusinessService.java

-Añadir todos los municipios e idiomas de la base de datos al back
-Modificar en el detalle de Negocio la visualización de los idiomas y municipios para que se vean correctamente y funcionen las correcciones

Gal 50- Añadir municipios e idiomas al Back y modificar la visulazación de los mismos en el detalle

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-detail/pack-detail.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-detail/pack-detail.component.html
cd2024bfs2g1-model/src/main/resources/dao/pack/PackDao.xml

No eliminar la rama al mergear! 👍

GAL-76 (Buttons & structure)

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-detail/routes-detail.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-home/routes-home.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-home/routes-home.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-new/view-all-landmark/view-all-landmark.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-routing.module.ts

Cuando se cree la ruta, se visualiza el detalle de la ruta.

GAL-101: Redirección al crear la ruta.

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-detail/routes-detail.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-detail/routes-detail.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-detail/view-landmark-detail/view-landmark-detail.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-detail/view-landmark-detail/view-landmark-detail.component.html

Landmarks ajustar el nombre
Guión en rutas details para cuando no hay duración
Flechas ajustarlas al lado del nombre

Modificaciones Routes detail y landmarks detail

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-new/pack-new.component.html

Minor Fix: days attr on pack-new.component.html

---

cd2024bfs2g1-api/src/main/java/com/campusdual/cd2024bfs2g1/api/core/service/IRouteService.java
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-new/add-activities/pack-routes/pack-routes.component.html
cd2024bfs2g1-model/src/main/java/com/campusdual/cd2024bfs2g1/model/core/service/RouteService.java

-Cambio de filtro de las rutas. De name a route_id.
Saludos G4
❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

FIX: GAL-58 route_id FILTER PACK

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-home/business-home.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-home/routes-home.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/en.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/es.json
cd2024bfs2g1-frontend/src/main/ngx/src/styles.scss
cd2024bfs2g1-model/src/main/resources/dao/RouteDao.xml

Tamaño campo ordenación, corrección filtro rutas, traducciones

GAL-G1-FIX: Arreglos finales

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-home/routes-home.component.ts

Corregido rutas

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-new/add-activities/pack-activities/pack-activities.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-new/add-activities/pack-routes/pack-routes.component.css

-Centrar el texto del comboBox de seleccionar días y el texto del botón de añadir negocios/rutas

GAL-58 centrar comboBox y botón 

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/my-packs/pack-client-detail/pack-client-detail.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/my-packs/pack-client-detail/pack-client-detail.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/en.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/es.json

-Mostrar el rango de fechas del pack reservado
Grupo 4<3🚀🚀🚀

UPDATE:GAL-58 show date range in the detail of the bookings

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/en.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/es.json

Nueva PR para tener la rama actualizada con dev

GAL-G5-fix

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/manage-packages/pack-edit/pack-edit.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/manage-packages/pack-edit/pack-edit.component.html

Cambios minimos en css y restriciones en la introduccion de valores en campos de texto

Cambios minimos en css y restriciones en la introduccion de valores en campos de texto

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-new/add-activities/pack-activities/pack-activities.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-new/add-activities/pack-routes/pack-routes.component.css

Arreglos en el css del PopUp de añadir negocios y rutas

GAL-58 arreglos css añadir negocios/rutas

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-detail/pack-detail.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-detail/pack-detail.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/en.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/es.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/gl.json

Booking pack button size
Pack home title font weight bold

GAL-108 - Minor Fixes

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-detail/pack-detail.component.html

Minor translation and styles fixes

GAL G5 Minor Style fixes 

---

cd2024bfs2g1-model/src/main/resources/db/migration/V14__link_bsn_rout_with_pck_and_alter_table_bsn_route_pack.sql

GAL-58 arreglo script v14

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-detail/pack-detail.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-detail/pack-detail.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-detail/pack-detail.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.ts

GAL-119 (Mejora usabilidad packs)

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-home/routes-home.component.ts

Arreglo del redirect desde packs hasta detalle de ruta para que se muestre el dialogo de detalle al recibir una url con id de ruta

Fix: Pack redirect to routes not opening dialog fixed

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/my-businesses/business-edit/business-edit.component.css

-Cambio en el tamaño de la letra en el botón de finalizar
Grupo 4<3🚀🚀🚀

Gal 56: Cambio de tamaño en el botón de finalizar

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.html

-Cambio botones del filtro de los packs
-Cambio orden de los filtros

cambio apariencia filtro de los packs

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-new/add-activities/add-activities.component.ts
cd2024bfs2g1-model/src/main/java/com/campusdual/cd2024bfs2g1/model/core/service/business/HotelService.java

-Se corrigio un bug al actualizar los servicios
-Corregido el error de estimated_duration en añadir rutas y negocios
Grupo4 <3🚀🚀🚀🚀

FIX:GAL-56 services update

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/graphics/graphics-home/graphics-home.component.css

- Se han ajustado las gráficas para cuando tienes una pantalla grande no se salgan de la carta principal

Ajuste de resolución de graphics

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/manage-packages/manage-all-packs/manage-all-packs.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/manage-packages/pack-edit/pack-edit.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/manage-packages/pack-edit/pack-edit.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/manage-packages/pack-edit/pack-edit.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/my-packs/pack-client/pack-client.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/my-packs/pack-client/pack-client.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes-manage/edit-route/edit-route.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes-manage/edit-route/edit-route.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes-manage/manage-all-routes/manage-all-routes.component.css

Cambio estilos titulo mis packs para coherencia
Quitada paginación tabla edit-route
Mapa con landmarks desde el principio
Coherencia de estilos entre pack-edit y route-edit y tamaño descripción controlada
Develop mergeado

GAL-G1-FIX

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/register/register-client/register-client.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/app/register/register-merchant/register-merchant.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/register/register-merchant/register-merchant.component.ts
cd2024bfs2g1-model/src/main/java/com/campusdual/cd2024bfs2g1/model/core/service/MerchantService.java
cd2024bfs2g1-model/src/main/java/com/campusdual/cd2024bfs2g1/model/core/service/UserAndRoleService.java

-Se ha corregido el error eliminando el submit del formulario, impidiendo que se realice el insert por duplicado y salte la restricción de clave única.
Grupo 4 <3 🚀🚀🧑‍🚒

Gal 128-Al registrarme, me dice que el usuario se ha insertado correctamente pero tambien que hubo error al insertar datos

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/login/login.component.html
cd2024bfs2g1-model/src/main/java/com/campusdual/cd2024bfs2g1/model/core/service/business/RestaurantService.java

Arreglado error:
-Se ha cambiado el tipo de los dos botones de registro en el login a type="button" para que no los recoja como un submit e intente lanzar el logeo del usuario.
Grupo 4 <3 🚀🚀🧑‍🚒

Gal 127 - Al ir al formulario de registro desde login, con usuario y password cubiertos, da error.

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-detail/pack-detail.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/en.json
charts/cd2024bfs2g1/values-dev.yaml

Redirect con funcionalidad completa para usuarios logeados, puede mejorar para usuarios no logeados, por ahora redirige a pack home.
Probamos 3 personas el redirect:
- A Marcos le redirige siempre a packhome cuando deberia ir a home
- A mi me pasa a veces y no es algo que sea capaz de replicar
- A Mathias le funciona bien 
Update: Faltaba un /main en los navigate haciendo que las redirecciones fueran inconsistentes

GAL G5 FIX (Mejora Redirección)

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.html

MINOR-STYLE-CHANGES 

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/graphics/graphics-home/graphics-home.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/graphics/graphics-home/graphics-home.component.html

Arreglo del responsive en analisis de datos

GAL-121 Arreglo del responsive en analisis de datos

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-detail/routes-detail.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/en.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/es.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/gl.json

- Traducciones routes detail
- Eliminado el punto de la descripción

GAL-121- FIX 

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-home/business-home.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/home/home.component.scss
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/my-businesses/business-merchant/business-merchant.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/my-packs/pack-client/pack-client.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-detail/pack-detail.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-home/routes-home.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/en.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/es.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/gl.json
charts/cd2024bfs2g1/values-dev.yaml

STYLE FIX 

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-home/business-home.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-home/business-home.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business.module.ts
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/my-businesses/business-merchant/business-merchant.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/my-businesses/business-merchant/business-merchant.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes.module.ts
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/en.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/es.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/gl.json

Añadimos los tooltips en Rutas, Business y my Business

GAL-121-FIX Añadimos los tooltips en Rutas, Business y my Business

---

cd2024bfs2g1-model/src/main/resources/dao/PackBookingDao.xml

Corrección orden gráficas packs mas/menos valorados

Correccion errores graficas V3

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-detail/view-landmark-detail/view-landmark-detail.component.html

- Eliminado el icono de la izquierda del mapa de view-landmarks

GAL-121-FIX

---

cd2024bfs2g1-model/src/main/java/com/campusdual/cd2024bfs2g1/model/core/service/pack/PackService.java

Solucionado error al mostrar la lista de días al añadir negocios y rutas a los packs.

FIX: pack days fixed

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-home/business-home.component.html

fix show deleted bsn

---

cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-new/pack-new.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-detail/routes-detail.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-detail/routes-detail.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-home/routes-home.component.css
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-home/routes-home.component.html

GENERAL FIXES

---

cd2024bfs2g1-boot/src/main/resources/application-local.yml
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/business/business-new/business-new.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-detail/pack-detail.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-detail/pack-detail.component.ts
cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-home/pack-home.component.html
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/en.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/es.json
cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/gl.json
cd2024bfs2g1-model/src/main/resources/dao/pack/PackDao.xml

- Redireccion cuando añadimos negocios
- Correcion de combo fechas
- Arreglo en visualizacion de los km
- Arreglo de los id en bbdd

FIX: some fixes
